### ISSUE TITLE
Latest changes not reflected on Maven Central

### ISSUE THREAD

**Issue by DazzyG** [Aghajari/LazyFlowLayout#2]
The [published](https://central.sonatype.com/artifact/io.github.aghajari/Flexbox-Compose/1.0.0/overview) version of the library is from the commit [1.0.0](https://github.com/Aghajari/LazyFlowLayout/commit/4c95b8bdeb698159e2de55bb1e61a4014c9671a8) and does not reflect the current state or the instructions in the readme.

Can you update the version on maven to match the current state/readme please

**Comment by Aghajari** [comment]
Hello @DazzyG ,
Thank you for reminding me to update!
Updated to v1.1.0

Note that the library name has changed from Flexbox to LazyFlowLayout.
