### ISSUE TITLE
Updating item list doesn't trigger items() recomposition

### ISSUE THREAD

**Issue by frankovlahov** [Aghajari/LazyFlowLayout#3]
Title says it all, the LazyFlowRow only works with initial set of data (a list), updating this list doesn't update the UI

**Comment by bazaar-android-interview** [comment]
Hi @frankovlahov .

make sure to use `mutableStateListOf` for your item list.

You can see a working example in the provided sample app.

```kotlin
val texts = remember {
    mutableStateListOf(*randomWords)
}

LaunchedEffect(Unit) {
    launch {
        delay(5000)
        texts.add("Test TIMER")
        texts.removeAt(0)
    }
}

LazyFlowRow {
    items(texts) {
     ...
    }
}
```

**Comment by Aghajari** [comment]
Hi @frankovlahov .

Make sure to use `mutableStateListOf` for your observable list!

Read more about [`SnapshotStateList`](https://developer.android.com/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotStateList) and [`mutableStateListOf`](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary?_gl=1*1tiuxtj*_up*MQ..*_ga*MTU2MTM1MzA2MC4xNzA5MzE0MTU1*_ga_6HH9YJMN9M*MTcwOTMxNDE1NC4xLjAuMTcwOTMxNDE1NC4wLjAuMA..#mutableStateListOf()).

You can see a working example in the provided sample app.

```kotlin
val texts = remember {
    mutableStateListOf(*randomWords)
}

LaunchedEffect(Unit) {
    launch {
        delay(5000)
        texts.add("Test")
        texts.removeAt(0)
    }
}

LazyFlowRow {
    items(texts) {
     ...
    }
}
```
